use_frameworks!
platform :ios, '10.0'

def shared_pods
    pod "MLDialogFlow", :path => "../"
    # Overriding ApiAI
    pod "ApiAI", :git => "git@github.com:metrolab/dialogflow-apple-client.git", :tag => "ml1.0.0"
end

target 'MLDialogFlow_Example' do
    shared_pods
end

target 'MLDialogFlow_Tests' do
    shared_pods
    
    pod "Quick", "~> 1.2.0"
    pod "Nimble", "~> 7.0.2"
    pod "RxTest", "~> 4.1.1"
end
